#!/usr/bin/env bash
# =============================================================================
# MOP Agent — Hetzner CX33 One-Shot Setup
# =============================================================================
# Run this ONCE on a fresh Ubuntu 22.04+ server as root (or with sudo).
#
#   curl -fsSL https://raw.githubusercontent.com/YOUR_ORG/YOUR_REPO/main/deploy/setup.sh | bash
#
#   — or —
#
#   scp deploy/setup.sh root@YOUR_SERVER_IP:~/
#   ssh root@YOUR_SERVER_IP "bash setup.sh"
#
# After it finishes, the app will be live at https://YOUR_DOMAIN.
# =============================================================================
set -euo pipefail

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}==>${NC} $*"; }
success() { echo -e "${GREEN}✓${NC} $*"; }
warn()    { echo -e "${YELLOW}!${NC} $*"; }
die()     { echo -e "${RED}✗ ERROR:${NC} $*" >&2; exit 1; }

[[ $EUID -eq 0 ]] || die "Run as root: sudo bash $0"

APP_DIR=/opt/mop-agent
SERVICE_NAME=mop-agent

# =============================================================================
# 1. Collect configuration
# =============================================================================
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${CYAN}  MOP Agent — Hetzner Setup${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

read -rp "GitHub repository URL (e.g. https://github.com/you/mop-agent): " GITHUB_REPO
[[ -n "$GITHUB_REPO" ]] || die "GitHub repo URL is required."

read -rp "Domain name (e.g. api.yourdomain.com — leave blank to use IP only): " DOMAIN
USE_SSL=false
if [[ -n "$DOMAIN" ]]; then
  USE_SSL=true
fi

read -rp "Email for SSL certificate (required if you entered a domain): " SSL_EMAIL

read -rsp "DeepSeek API key: " DEEPSEEK_API_KEY; echo
[[ -n "$DEEPSEEK_API_KEY" ]] || die "DEEPSEEK_API_KEY is required."

read -rp "Vercel frontend URL (e.g. https://mop.vercel.app — leave blank to allow all origins): " FRONTEND_URL

# Generate a cryptographically random JWT secret
JWT_SECRET=$(openssl rand -hex 32)
success "Generated JWT secret."

echo ""
info "Configuration summary:"
echo "  Repo:    $GITHUB_REPO"
echo "  Domain:  ${DOMAIN:-<IP only, no SSL>}"
echo "  SSL:     $USE_SSL"
echo "  Origins: ${FRONTEND_URL:-* (all origins)}"
echo ""
read -rp "Continue? [y/N] " CONFIRM
[[ "${CONFIRM,,}" == "y" ]] || die "Aborted."

# =============================================================================
# 2. System packages
# =============================================================================
info "Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq

info "Installing dependencies..."
apt-get install -y -qq \
  ca-certificates \
  curl \
  gnupg \
  lsb-release \
  git \
  nginx \
  ufw \
  certbot \
  python3-certbot-nginx \
  openssl

# Docker via official apt repo
if ! command -v docker &>/dev/null; then
  info "Installing Docker..."
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg
  echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list
  apt-get update -qq
  apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin
else
  success "Docker already installed: $(docker --version)"
fi

systemctl enable --now docker
success "Docker running."

# =============================================================================
# 3. Firewall
# =============================================================================
info "Configuring UFW firewall..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow OpenSSH
ufw allow 'Nginx Full'   # ports 80 + 443
ufw --force enable
success "Firewall configured (SSH + HTTP/HTTPS open)."

# =============================================================================
# 4. Clone the repository
# =============================================================================
info "Cloning repository to $APP_DIR..."
if [[ -d "$APP_DIR/.git" ]]; then
  warn "$APP_DIR already exists. Pulling latest..."
  git -C "$APP_DIR" pull --ff-only
else
  git clone "$GITHUB_REPO" "$APP_DIR"
fi
success "Repository ready."

# =============================================================================
# 5. Create .env file
# =============================================================================
info "Creating production .env file..."
ALLOWED_ORIGINS="${FRONTEND_URL:-*}"
TRUSTED_HOSTS="${DOMAIN:-localhost}"

cat > "$APP_DIR/.env" <<EOF
# ── Auto-generated by deploy/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) ──

DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
DEEPSEEK_BASE_URL=https://api.deepseek.com
DEEPSEEK_MODEL=deepseek-chat
DEEPSEEK_REASONER_MODEL=deepseek-reasoner
DEEPSEEK_TIMEOUT=45

APP_VERSION=1.0.0

# Authentication — KEEP THIS SECRET
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRY_SECONDS=86400

# Databases (persisted in Docker volume mop-data)
SQLITE_DB_PATH=/app/data/runtime/mop.sqlite3
DUCKDB_PATH=/app/data/runtime/mop.duckdb

# SQL agent tuning
SQL_MAX_TOKENS=1400
SQL_REPAIR_ATTEMPTS=3
SQL_REPAIR_MODELS=deepseek-chat,deepseek-reasoner
SQL_PREFLIGHT_ENABLED=1
RESULT_VALIDATION_ENABLED=1
STRUCTURED_SQL_ENABLED=1

# Answer formatting
FORMATTER_MAX_TOKENS=4000
CONCEPTUAL_MAX_TOKENS=1800
MIN_ANALYTIC_WORDS=150
FORMATTER_PREVIEW_ROWS=60
MAX_RETURN_ROWS=250
DEFAULT_TOP_K=15
MAX_TOP_K=50

# Network / CORS
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
TRUSTED_HOSTS=${TRUSTED_HOSTS},localhost,127.0.0.1
GZIP_MINIMUM_SIZE=1000
UVICORN_WORKERS=1
LOG_LEVEL=info
EOF
chmod 600 "$APP_DIR/.env"
success ".env created."

# =============================================================================
# 6. Nginx configuration
# =============================================================================
info "Configuring Nginx..."

# Rate-limit zone (must be in http context)
cat > /etc/nginx/conf.d/rate-limit.conf <<'EOF'
limit_req_zone $binary_remote_addr zone=api:10m rate=30r/m;
limit_req_zone $binary_remote_addr zone=auth:10m rate=10r/m;
EOF

# Site config — HTTP first (certbot will upgrade to HTTPS)
NGINX_SITE=/etc/nginx/sites-available/$SERVICE_NAME
PROXY_TARGET="http://127.0.0.1:8000"
SERVER_NAME="${DOMAIN:-_}"

cat > "$NGINX_SITE" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAME};

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect all HTTP → HTTPS once cert exists
    # (certbot --nginx will update this block automatically)

    # ── Proxy to Docker container ──

    location /health {
        proxy_pass $PROXY_TARGET/health;
        proxy_set_header Host \$host;
        access_log off;
        proxy_read_timeout 10s;
    }

    location /api/auth/ {
        limit_req zone=auth burst=5 nodelay;
        proxy_pass $PROXY_TARGET;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 30s;
    }

    location /api/ {
        limit_req zone=api burst=10 nodelay;
        proxy_pass $PROXY_TARGET;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
        proxy_buffering off;
    }

    location / {
        proxy_pass $PROXY_TARGET;
        proxy_set_header Host              \$host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade           \$http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_read_timeout 120s;
    }

    client_max_body_size 2m;
}
EOF

# Enable the site
rm -f /etc/nginx/sites-enabled/default
ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/$SERVICE_NAME

nginx -t
systemctl enable --now nginx
systemctl reload nginx
success "Nginx configured."

# =============================================================================
# 7. Build and start the Docker container
# =============================================================================
info "Building and starting Docker container (this may take a few minutes)..."
cd "$APP_DIR"
docker compose up -d --build
success "Container started."

# Wait for health check
info "Waiting for health check..."
for i in {1..30}; do
  if curl -sf http://localhost:8000/health > /dev/null 2>&1; then
    success "Health check passed."
    break
  fi
  if [[ $i -eq 30 ]]; then
    warn "Health check timed out. Check logs: docker compose -f $APP_DIR/docker-compose.yml logs"
  fi
  sleep 2
done

# =============================================================================
# 8. SSL with Certbot (optional)
# =============================================================================
if $USE_SSL && [[ -n "$DOMAIN" ]] && [[ -n "$SSL_EMAIL" ]]; then
  info "Obtaining SSL certificate for $DOMAIN..."
  mkdir -p /var/www/certbot
  certbot --nginx \
    -d "$DOMAIN" \
    --email "$SSL_EMAIL" \
    --agree-tos \
    --non-interactive \
    --redirect
  success "SSL certificate installed."

  # Certbot auto-renewal
  systemctl enable --now certbot.timer 2>/dev/null || \
    (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet") | crontab -
  success "Certbot auto-renewal configured."
else
  warn "Skipping SSL — app running on HTTP only."
  [[ -z "$DOMAIN" ]] && warn "Set a domain and run: certbot --nginx -d YOUR_DOMAIN"
fi

# =============================================================================
# 9. Final summary
# =============================================================================
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}  MOP Agent is live!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
if $USE_SSL && [[ -n "$DOMAIN" ]]; then
  echo -e "  Backend:   ${CYAN}https://${DOMAIN}${NC}"
else
  SERVER_IP=$(curl -sf https://api.ipify.org || echo "<your-server-ip>")
  echo -e "  Backend:   ${CYAN}http://${SERVER_IP}${NC}  (no SSL yet)"
fi
echo -e "  Health:    curl $([ "$USE_SSL" = "true" ] && echo https || echo http)://${DOMAIN:-localhost}/health"
echo -e "  Logs:      docker compose -f $APP_DIR/docker-compose.yml logs -f"
echo -e "  Redeploy:  bash $APP_DIR/deploy/redeploy.sh"
echo ""
echo -e "${YELLOW}NEXT STEP — Deploy the frontend on Vercel:${NC}"
echo "  1. Push your repo to GitHub (including data/parquet/ files)"
echo "  2. Connect the repo on vercel.com → Framework: Vite → Root Dir: frontend"
echo "  3. Add Vercel env var: VITE_API_BASE_URL = https://${DOMAIN:-YOUR_DOMAIN}"
echo "  4. Deploy. Done."
echo ""
echo -e "${YELLOW}After Vercel deploy, update ALLOWED_ORIGINS on this server:${NC}"
echo "  1. Edit $APP_DIR/.env → set ALLOWED_ORIGINS=https://YOUR_VERCEL_URL"
echo "  2. docker compose -f $APP_DIR/docker-compose.yml restart"
echo ""
